"use client";
import {useEffect,useState,type FormEvent} from "react";
import {AdminShell} from "../../components/admin-shell";
type Coupon={id:string;code:string;percentOff:number;maxRedemptions:number|null;redemptionCount:number;expiresAt:string|null;isActive:boolean};
export default function Page(){
 const[coupons,setCoupons]=useState<Coupon[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){const response=await fetch("/api/coupons",{cache:"no-store"});if(response.ok)setCoupons((await response.json()).coupons)}
 useEffect(()=>{let active=true;fetch("/api/coupons",{cache:"no-store"}).then(async response=>{const data=response.ok?await response.json():null;if(active&&data)setCoupons(data.coupons)});return()=>{active=false}},[]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);setError("");try{const values=Object.fromEntries(new FormData(form).entries()),response=await fetch("/api/coupons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)}),result=await response.json();if(!response.ok)setError(result.error==="CODE_EXISTS"?"This coupon code already exists.":"Check the coupon fields.");else{form.reset();await load()}}catch{setError("Coupon could not be created. Please try again.")}finally{setBusy(false)}}
 async function toggle(coupon:Coupon){await fetch("/api/coupons",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:coupon.id,isActive:!coupon.isActive})});await load()}
 return <AdminShell name="Super administrator"><main className="p-5 lg:p-7"><h1 className="text-2xl font-bold">Coupons</h1><p className="text-sm text-[var(--muted)]">Create recurring monthly discounts. A 100% coupon creates complimentary access without PayPal.</p><form onSubmit={create} className="mt-6 grid gap-4 rounded-xl border bg-white p-5 md:grid-cols-4"><Field name="code" label="Coupon code" placeholder="WELCOME50"/><Field name="percentOff" label="Discount %" type="number" min="1" max="100"/><Field name="maxRedemptions" label="Usage limit (optional)" type="number" min="1" optional/><Field name="expiresAt" label="Redeem before (optional)" type="date" optional/>{error?<p className="text-sm text-red-600 md:col-span-4">{error}</p>:null}<button disabled={busy} className="cursor-pointer rounded-lg bg-[var(--accent)] px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50 md:col-span-4 md:justify-self-start">{busy?"Creating…":"Create coupon"}</button></form><section className="mt-6 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-[#f8f7f5] text-xs text-[var(--muted)]"><tr><th className="p-4">Code</th><th>Recurring discount</th><th>Usage</th><th>Expires</th><th>Status</th><th/></tr></thead><tbody>{coupons.map(c=><tr key={c.id} className="border-t"><td className="p-4 font-mono font-bold">{c.code}</td><td>{c.percentOff}% every month</td><td>{c.redemptionCount} / {c.maxRedemptions??"Unlimited"}</td><td>{c.expiresAt?new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date(c.expiresAt)):"Never"}</td><td className={c.isActive?"text-green-700":"text-gray-500"}>{c.isActive?"Active":"Disabled"}</td><td className="pr-4 text-right"><button onClick={()=>void toggle(c)} className="cursor-pointer rounded-lg border px-3 py-1.5 text-xs font-bold">{c.isActive?"Disable":"Enable"}</button></td></tr>)}</tbody></table>{!coupons.length?<p className="p-8 text-center text-sm text-[var(--muted)]">No coupons created yet.</p>:null}</section></main></AdminShell>}
function Field({name,label,type="text",placeholder,min,max,optional=false}:{name:string;label:string;type?:string;placeholder?:string;min?:string;max?:string;optional?:boolean}){return <label className="text-xs font-bold">{label}<input name={name} required={!optional} type={type} placeholder={placeholder} min={min} max={max} className="mt-1.5 w-full rounded-lg border px-3 py-2.5 uppercase"/></label>}
