import "server-only";

function required(name: string) { const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is not configured.`);return value; }
function baseUrl(){return process.env.PAYPAL_ENVIRONMENT==="live"?"https://api-m.paypal.com":"https://api-m.sandbox.paypal.com"}
async function token(){const credentials=Buffer.from(`${required("PAYPAL_CLIENT_ID")}:${required("PAYPAL_CLIENT_SECRET")}`).toString("base64");const response=await fetch(`${baseUrl()}/v1/oauth2/token`,{method:"POST",headers:{Authorization:`Basic ${credentials}`,"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials",cache:"no-store"});if(!response.ok)throw new Error(`PayPal authentication failed (${response.status}).`);const data=await response.json() as{access_token?:string};if(!data.access_token)throw new Error("PayPal access token missing.");return data.access_token}
async function request<T>(path:string,init:RequestInit={}){const accessToken=await token(),response=await fetch(`${baseUrl()}${path}`,{...init,headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json",Prefer:"return=representation",...(init.headers||{})},cache:"no-store"});if(!response.ok){const detail=await response.text().catch(()=>"");console.error("PayPal admin API error",response.status,path,detail.slice(0,1000));throw new Error(`PayPal request failed (${response.status}).`)}return response.status===204?undefined as T:await response.json() as T}
export async function createProduct(name:string){return request<{id:string}>("/v1/catalogs/products",{method:"POST",headers:{"PayPal-Request-Id":`qualityfriend-product-${Date.now()}`},body:JSON.stringify({name,description:"QualityFriend hotel operations SaaS subscription",type:"SERVICE",category:"SOFTWARE"})})}
export async function createPlan(productId:string,name:string,price:string){return request<{id:string,status:string}>("/v1/billing/plans",{method:"POST",headers:{"PayPal-Request-Id":`qualityfriend-plan-${Date.now()}`},body:JSON.stringify({product_id:productId,name,description:"QualityFriend full hotel access",status:"ACTIVE",billing_cycles:[{frequency:{interval_unit:"MONTH",interval_count:1},tenure_type:"REGULAR",sequence:1,total_cycles:0,pricing_scheme:{fixed_price:{value:price,currency_code:"EUR"}}}],payment_preferences:{auto_bill_outstanding:true,payment_failure_threshold:3}})})}
export async function updatePlanPrice(planId:string,price:string){await request<void>(`/v1/billing/plans/${encodeURIComponent(planId)}/update-pricing-schemes`,{method:"POST",body:JSON.stringify({pricing_schemes:[{billing_cycle_sequence:1,pricing_scheme:{fixed_price:{value:price,currency_code:"EUR"}}}]})})}
